### ISSUE TITLE
Feature request: Add a keyboard shortcut to change focus from the address bar to Tabash.

### ISSUE THREAD

**Issue by deopard** [j-jiseophan/tabash#19]
Chrome automatically sets focus to the address bar when a new tab opens.
There are times when using tabash is handy and entering a direct address is handy. Please add a keyboard shortcut to focus on tabash.

**Comment by j-jiseophan** [comment]
https://github.com/j-jiseophan/tabash/releases/tag/0.7.0
From 0.7.0 focus is set to tabash by default. thanks!

**Comment by deopard** [comment]
@j-jiseophan Thx for the quick merge!
When will this version be uploaded to Chrome Web Store?

**Comment by j-jiseophan** [comment]
@deopard chrome webstore review approved just before 🙂
https://chrome.google.com/webstore/detail/tabash/kkfnmemgenijggeklnbaoomnbongmlie?hl=ko
