### ISSUE TITLE
새탭 열시 주소창 focus 사라짐

### ISSUE THREAD

**Issue by yongsk0066** [j-jiseophan/tabash#20]
기존에는 새탭열면 주소창으로 focus가 되었던거 같은데,
 업데이트 이후는 익스텐션 uri가 표시됩니다

<img width="685" alt="스크린샷 2022-01-14 오전 9 14 17" src="https://user-images.githubusercontent.com/46309806/149429215-35e60d0a-a145-4be7-a592-acca0190a3e9.png">

**Comment by j-jiseophan** [comment]
크롬 탭 익스텐션 정책상 유저가 화면을클릭 하기 전까지는 인풋에 포커스를 주는게 불가능했기때문에 이를 우회하기 위해 새 페이지를 띄운후 포커스를 준겁니다~
